server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE

spring.datasource:
  name: springdb
  url: jdbc:mysql://localhost:3306/springdb
  username: root
  password: rahulrj
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  hibernate.ddl-auto: update
  show-sql: true

