server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

spring.datasource:
  name: springdb
  url: jdbc:mysql://localhost:3306/springdb
  username: root
  password: rahulrj
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  hibernate.ddl-auto: update
  show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost